version: "3.8"

services:
  configserver:
    image: configserver-app
    ports:
      - "8071:8071"
    networks:
      - microservices
    environment:
      SPRING_PROFILES_ACTIVE: default

  discoveryserver:
    image: discoveryserver-app
    ports:
      - "8070:8070"
    networks:
      - microservices
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: account-app
    ports:
      - "8080:8080"
    networks:
      - microservices
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/

  loan:
    image: loan-app
    ports:
      - "8082:8082"
    networks:
      - microservices
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/

  card:
    image: card-app
    ports:
      - "8081:8081"
    networks:
      - microservices
    depends_on:
      - configserver
      - discoveryserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discoveryserver:8070/eureka/


networks:
  microservices: