apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: account-app
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb+srv://hoangvananh7201:29md381860@cluster0.l6mlo37.mongodb.net/MS_account?retryWrites=true&w=majority
          imagePullPolicy: Always

---
# microservice.yaml
apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  selector:
    app: account
  ports:
    - port : 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
